apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: dktplatform-booking-website
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dktplatform-booking-website
  progressDeadlineSeconds: 180
  service:
    port: 80
    portName: http
    gateways:
    - allforsport-cn.istio-system.svc.cluster.local
    hosts:
    - booking-website-dev.allforsport.cn
  revertOnDeletion: true
  analysis:
    interval: 30s
    threshold: 10
    maxWeight: 80
    stepWeight: 10
    metrics:
    - name: istio_requests_total
      threshold: 99
      interval: 1m
    webhooks:
      - name: load-test-get
        type: pre-rollout
        url: http://flagger-loadtester.dev/
        timeout: 5s
        metadata:
          type: cmd
          cmd: "hey -z 1m -q 10 -c 2 http://dktplatform-booking-website-canary.dev/"
