apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: guestbook-ui
  namespace: dev
spec:
  gateways:
  - istio-system/allforsport-cn
  hosts:
  - guestbook-ui-dev.allforsport.cn
  http:
  - route:
    - destination:
        host: guestbook-ui.dev.svc.cluster.local
        port:
          number: 80
